# Generated by Django 3.1.7 on 2021-04-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nameFamily', models.CharField(max_length=100)),
                ('nameGiven', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('profilePicture', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('onBreak', models.BooleanField()),
                ('breakTime', models.FloatField()),
                ('currentChat', models.CharField(max_length=100)),
            ],
        ),
    ]
